title: Alexandra Bugariu
description: <li><a href="https://www.linkedin.com/in/alexandra-olimpia-bugariu-5b7a22bb/"><i class="fab fa-fw fa-linkedin"></i> LinkedIn</a></li> <li><a href="https://scholar.google.com/citations?user=JdjIePAAAAAJ&hl=en"><i class="fas fa-fw fa-graduation-cap"></i> Google Scholar</a></li> bugariua@mpi-sws.org, alexandra.bugariu@inf.ethz.ch
remote_theme: pages-themes/cayman@v0.2.0
