title: Alexandra Bugariu
description: <a href="mailto:bugariua@mpi-sws.org"><i class="fa fa-envelope"></i></a> <a href="https://www.linkedin.com/in/alexandra-olimpia-bugariu-5b7a22bb/"><i class="fa fa-linkedin"></i></a> <a href="https://scholar.google.com/citations?user=JdjIePAAAAAJ&hl=en"><i class="ai ai-google-scholar big-icon"></i></a>
remote_theme: pages-themes/cayman@v0.2.0
