title: Alexandra Bugariu
description: <a href="https://www.linkedin.com/in/alexandra-olimpia-bugariu-5b7a22bb/"><i class="fab fa-linkedin-in"></i> LinkedIn</a> <a href="https://scholar.google.com/citations?user=JdjIePAAAAAJ&hl=en"><i class="fas fa-fw fa-graduation-cap"></i> Google Scholar</a> bugariua@mpi-sws.org, alexandra.bugariu@inf.ethz.ch
remote_theme: pages-themes/cayman@v0.2.0
