title: Alexandra Bugariu
description: <a href="mailto:bugariua@mpi-sws.org"><i class="fa fa-envelope"></i></a> &nbsp; <a href="https://scholar.google.com/citations?user=JdjIePAAAAAJ&hl=en"><i class="fa fa-graduation-cap"></i></a> &nbsp; <a href="https://www.linkedin.com/in/alexandra-olimpia-bugariu-5b7a22bb/"><i class="fa fa-linkedin"></i></a> &nbsp; <a href="https://github.com/alebugariu"><i class="fa fa-github"></i></a>
remote_theme: pages-themes/cayman@v0.2.0
